export const TEMPLATES = [
  {
    id: 'ramadan_edition',
    name: 'Ramadan Edition',
    description: 'Специальная коллекция к Рамадану',
    badge: 'Хит',
    badgeColor: 'bg-amber-500',
    image: null,   // ← поставь путь к фото когда файл появится
    config: {
      color: 'emerald',
      material: 'silk',
      pattern: 'classic_mihrab',
      border: 'ornate',
      size: 'standard',
      text: '',
      textFont: 'arabic',
      textColor: '#F5D48A',
      tassels: true,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'premium_gold',
    name: 'Premium Gold',
    description: 'Роскошный бежевый с золотыми узорами',
    badge: 'Люкс',
    badgeColor: 'bg-gold-500',
    config: {
      color: 'beige',
      material: 'silk',
      pattern: 'arabesque',
      border: 'ornate',
      size: 'standard',
      text: '',
      textFont: 'playfair',
      textColor: '#8B6914',
      tassels: true,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'minimal_black',
    name: 'Minimal Black',
    description: 'Элегантный минимализм без лишних деталей',
    badge: null,
    badgeColor: null,
    config: {
      color: 'black',
      material: 'velour',
      pattern: 'minimal',
      border: 'simple',
      size: 'standard',
      text: '',
      textFont: 'inter',
      textColor: '#C9A227',
      tassels: false,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'turkish_style',
    name: 'Turkish Style',
    description: 'Традиционный турецкий орнамент',
    badge: 'Турция',
    badgeColor: 'bg-red-600',
    config: {
      color: 'dark_blue',
      material: 'turkish',
      pattern: 'geometric',
      border: 'double',
      size: 'standard',
      text: '',
      textFont: 'playfair',
      textColor: '#C9A227',
      tassels: true,
      tasselColor: '#F5D48A',
    },
  },
  {
    id: 'kazakh_heritage',
    name: 'Kazakh Heritage',
    description: 'Казахский национальный орнамент',
    badge: 'Казахстан',
    badgeColor: 'bg-sky-600',
    config: {
      color: 'dark_green',
      material: 'velvet',
      pattern: 'kazakh',
      border: 'ornate',
      size: 'standard',
      text: '',
      textFont: 'playfair',
      textColor: '#C9A227',
      tassels: true,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'royal_burgundy',
    name: 'Royal Burgundy',
    description: 'Бордовый бархат с цветочным орнаментом',
    badge: null,
    badgeColor: null,
    config: {
      color: 'burgundy',
      material: 'velvet',
      pattern: 'floral',
      border: 'classic',
      size: 'standard',
      text: '',
      textFont: 'playfair',
      textColor: '#F5D48A',
      tassels: true,
      tasselColor: '#F5D48A',
    },
  },
  {
    id: 'emerald_mosque',
    name: 'Emerald Mosque',
    description: 'Изумрудный с силуэтом мечети',
    badge: 'Новинка',
    badgeColor: 'bg-emerald-600',
    config: {
      color: 'emerald',
      material: 'velvet',
      pattern: 'mosque',
      border: 'classic',
      size: 'standard',
      text: '',
      textFont: 'arabic',
      textColor: '#F5D48A',
      tassels: false,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'classic_teal',
    name: 'Classic Teal',
    description: 'Бирюзовый с классическим михрабом',
    badge: null,
    badgeColor: null,
    config: {
      color: 'teal',
      material: 'cotton',
      pattern: 'classic_mihrab',
      border: 'classic',
      size: 'standard',
      text: '',
      textFont: 'inter',
      textColor: '#F5D48A',
      tassels: false,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'midnight_arabian',
    name: 'Midnight Arabian',
    description: 'Тёмно-синий с арабеской',
    badge: null,
    badgeColor: null,
    config: {
      color: 'dark_blue',
      material: 'memory_foam',
      pattern: 'arabesque',
      border: 'ornate',
      size: 'large',
      text: '',
      textFont: 'arabic',
      textColor: '#C9A227',
      tassels: true,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'children_green',
    name: 'Детский Зелёный',
    description: 'Яркий и лёгкий детский коврик',
    badge: 'Детский',
    badgeColor: 'bg-green-500',
    config: {
      color: 'dark_green',
      material: 'cotton',
      pattern: 'mosque',
      border: 'simple',
      size: 'child',
      text: '',
      textFont: 'inter',
      textColor: '#F5D48A',
      tassels: false,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'gift_gold',
    name: 'Подарочный Золотой',
    description: 'Идеальный подарок в фирменной коробке',
    badge: 'Подарок',
    badgeColor: 'bg-amber-600',
    config: {
      color: 'dark_green',
      material: 'silk',
      pattern: 'arabesque',
      border: 'ornate',
      size: 'gift',
      text: '',
      textFont: 'playfair',
      textColor: '#F5D48A',
      tassels: true,
      tasselColor: '#C9A227',
    },
  },
  {
    id: 'gray_minimal',
    name: 'Gray Minimal',
    description: 'Серый нейтральный минимализм',
    badge: null,
    badgeColor: null,
    config: {
      color: 'gray',
      material: 'velour',
      pattern: 'minimal',
      border: 'double',
      size: 'standard',
      text: '',
      textFont: 'inter',
      textColor: '#C9A227',
      tassels: false,
      tasselColor: '#C9A227',
    },
  },
];
